### PR TITLE
copyediting

### PR DESCRIPTION
**Pull request by robbyoconnor**

### CODE REVIEW

**Comment by jomaxro** [comment]
The current copy appears correct to me.  The complete sentence is `Please select or create one.` so the `c` in create should indeed be lowercase.

**Comment by robbyoconnor** [comment]
I guess the question would be why isn't the whole sentence here?

**Comment by jomaxro** [comment]
The sentence is broken up because only "create one" is a link. If the translation was a single sentence we'd have to make the entire sentence a link.

**Comment by robbyoconnor** [comment]
nevermind then :)

**Pull request closed without merging**
